on:
  workflow_call:
    inputs:
      artifact-path:
        required: true
        type: string
      artifact-name:
        required: true
        type: string
    secrets:
      client_id:
        required: true
      tenant_id:
        required: true
      subscription_id:
        required: true
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.example_job.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.example_job.outputs.output2 }}

jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    # Map the job outputs to step outputs
    outputs:
      output1: ${{ steps.step1.outputs.firstword }}
      output2: ${{ steps.step2.outputs.secondword }}
    steps:
      - id: step1
        run: echo "firstword=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "The artifact-name is ${{ inputs.artifact-name }}" >> $GITHUB_OUTPUT
